build_script:
  - mkdir blf\storage\title\4d530877\tracked\106708
  - mkdir blf\storage\title\4d53085b\tracked\12065
  - mkdir blf\storage\title\4d530877\tracked\13895
  - mkdir blf\storage\title\tracked\12070
  - mkdir blf\storage\title\tracked\11856
  - mkdir blf\storage\title\tracked\11855
  - mkdir blf\storage\title\tracked\11729
  - mkdir blf\storage\title\tracked\10015
  - mkdir blf\storage\title\tracked\09699
  - mkdir blf\storage\title\tracked\08172
  - mkdir blf\storage\title\tracked\06481
  - tools\SunriseBlfTool.exe blf json\storage\title\4d530877\tracked\106708 blf\storage\title\4d530877\tracked\106708 106708
  - tools\SunriseBlfTool.exe blf json\storage\title\4d53085b\tracked\12065 blf\storage\title\4d53085b\tracked\12065 reach_12065
  - tools\SunriseBlfTool.exe blf json\storage\title\4d530877\tracked\13895 blf\storage\title\4d530877\tracked\13895 13895
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\12070 blf\storage\title\tracked\12070 12070
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\12070 blf\storage\title\tracked\11855 11855
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\11856 blf\storage\title\tracked\11856 11856
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\11729 blf\storage\title\tracked\11729 11729
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\10015 blf\storage\title\tracked\10015 10015
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\09699 blf\storage\title\tracked\09699 09699
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\08172 blf\storage\title\tracked\08172 08172
  - tools\SunriseBlfTool.exe blf json\storage\title\tracked\06481 blf\storage\title\tracked\06481 06481
  - 7z a content.zip .\json\*
  - 7z a content.zip .\blf\*
artifacts:
  - path: "**/content.zip"
    name: Content

on_success:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\Sunrise-Content\build_scripts\discord-webhook.ps1 success $env:DISCORD_WEBHOOK_URL}
on_failure:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\Sunrise-Content\build_scripts\discord-webhook.ps1 failure $env:DISCORD_WEBHOOK_URL}

deploy_script:
  #- ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\Sunrise-Content\build_scripts\trigger-redeploy.ps1}
